framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            sluggable: true
            tree: true
            translatable: true
    translation_fallback: true

sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

# TODO: configuration
sonata_translation:
    locales: [en, ru]
    default_locale: %locale%
    gedmo:
        enabled: true
