version: '3.4'

services:
    app:
        build:
            context: .
            dockerfile: ./support/ci/Dockerfile
        container_name: blogbundle_app
        links:
            - mysql
        volumes:
            - ./:/app
        links:
            - mysql

    mysql:
        image: mysql
        container_name: blogbundle_mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1111
            MYSQL_PASSWORD: 1111
            MYSQL_DATABASE: blog
        command: mysqld --sql-mode=''

    selenium:
        image: selenium/standalone-chrome
        links:
            - nginx

    nginx:
        image: nginx
        volumes:
            - ./:/app
            - ./support/ci/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        links:
            - app
